# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  VITE_EVENT_TIME: ${{ secrets.VITE_EVENT_TIME }}
  VITE_EVENT_LOCATION: ${{ secrets.VITE_EVENT_LOCATION }}
  VITE_EMAILJS_PUBKEY: ${{ secrets.VITE_EMAILJS_PUBKEY }}
  VITE_EMAILJS_TEMPLATEID: ${{ secrets.VITE_EMAILJS_TEMPLATEID }}
  VITE_EMAILJS_SERVICEID: ${{ secrets.VITE_EMAILJS_SERVICEID }}
  VITE_PASSWORD: ${{ secrets.VITE_PASSWORD }}

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          cache: false
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
